#!/usr/bin/env bash

is_exists() {
    type "$1" > /dev/null 2>&1
    return $?
}


if [ -z "${DOTPATH:-}" ]; then
    DOTPATH="${HOME}/.dotfiles"
fi
DOTFILE_GITHUB="https://github.com/nacl30d/dotfiles"

dotfiles_download() {
    if [ -d "$DOTPATH" ]; then
        echo "Error: $DOTPATH: already exists"
        exit 1
    fi

    if is_exists "git"; then
        git clone "${DOTFILE_GITHUB}.git" "${DOTPATH}"
    elif is_exists "curl"; then
        curl -LO "${DOTFILE_GITHUB}/archive/master.tar.gz"
        tar zxvf master.tar.gz "${DOTPATH}"
    else
        echo 'Required: git or curl'
        exit 1;
    fi
    echo "Success Download"
}

dotfiles_deploy() {
    echo "Deploying dotfiles..."

    if [ ! -d $DOTPATH ]; then
        echo "Error: $DOTPATH: not found"
        exit 1
    fi

    cd "$DOTPATH"
    make deploy
    echo "Success Deploy"
}

# A script for the file named "install"
dotfiles_install() {
    dotfiles_download &&
    dotfiles_deploy
}

dotfiles_install
